#language: c

addons:
  homebrew:
    update: false

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="k get nodes -o wide"

install:
  - eval "${MATRIX_EVAL}"