language: c

addons:
  homebrew:
    update: true

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

install:
  - eval "${MATRIX_EVAL}"